version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
{% if extras_includes('sqlite') -%}
    environment:
      - DATABASE_URL=postgresql://app:supersafepassword@db:5432/app
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=supersafepassword
      - POSTGRES_DB=app
    expose:
      - 5432
{% endif -%}
